[build]
  command = "echo 'No build command needed'"
  publish = "."

[[redirects]]
  from = "/"
  to = "/Fire-Doomlings-App.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/settings.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/Fire-Doomlings-App.html"
  status = 200

[build.environment]
  NODE_VERSION = "16" 